MESSAGE("Specialized FindBROTLI Called")
if( NOT $ENV{BROTILIDEC_LIBRARY} STREQUAL "" )
  SET(BROTILIDEC_LIBRARY $ENV{BROTILIDEC_LIBRARY})

  if( NOT $ENV{BROTILIENC_LIBRARY} STREQUAL "" )
  	SET(BROTILIENC_LIBRARY $ENV{BROTILIENC_LIBRARY})
  endif()

  if( NOT $ENV{BROTILIDEC_LIBRARY} STREQUAL "" )
  	SET(BROTILIDEC_LIBRARY $ENV{BROTILIDEC_LIBRARY})
  endif()

  set(BROTLI_LIBRARIES ${BROTILIDEC_LIBRARY} ${BROTILIENC_LIBRARY} ${BROTILIDEC_LIBRARY})

  if( NOT $ENV{BROTILI_INCLUDE_DIR} STREQUAL "" )
     SET(BROTLI_INCLUDE_DIR $ENV{BROTILI_INCLUDE_DIR})
     SET(BROTIL_DIR $ENV{BROTILI_INCLUDE_DIR})
  endif()


  mark_as_advanced(BROTLI_LIBRARIES BROTLI_INCLUDE_DIR, BROTIL_DIR)

  SET(BROTLI_FOUND TRUE)

  MESSAGE("FindBROTLI Set By Envionment")


endif()